/* eslint-disable */
const xillia = {
  "jude": {
    "healer": {
      "Arte Name": "Healer",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Psyche",
      "Damage Effect": "-",
      "Damage Spread": "-",
      "Total Damage (%)": "-",
      "Max Hits": "-",
      "TP Cost": "5",
      "Requirements": "-",
      "Description": "heals all allies within range in two burstsheals between 24% and 12% of max HP at a rate of 12% to 6% HP per burst depending on the distance from Judeaction speed increases after 100 and 400 useshealing range increases after 200 uses"
    },
    "recovery ring": {
      "Arte Name": "Recovery Ring",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "-",
      "Total Damage (%)": "-",
      "Max Hits": "-",
      "TP Cost": "13",
      "Requirements": "Lilium Orb: Orb 1 Node 4",
      "Description": "cures all negative status ailments for all allies within a small rangeaction speed increases after 100 and 400 useshealing range increases after 200 uses"
    },
    "demon fist": {
      "Arte Name": "Demon Fist",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "0.34 x 11.70 x 1",
      "Total Damage (%)": "204",
      "Max Hits": "2",
      "TP Cost": "6",
      "Requirements": "-",
      "Description": "projectile speed and range increase after 100 and 200 usesthe projectile penetrates targets after 400 uses"
    },
    "cerberus strike": {
      "Arte Name": "Cerberus Strike",
      "Enabled Effects": "-",
      "Elemental Attributes": "Earth",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Slow",
      "Damage Spread": "1.00 x 3",
      "Total Damage (%)": "300",
      "Max Hits": "3",
      "TP Cost": "9",
      "Requirements": "Lilium Orb: Orb 1 Node 1",
      "Description": "attack speed increases after 200 uses"
    },
    "steel": {
      "Arte Name": "Steel",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "2.00 x 1",
      "Total Damage (%)": "200",
      "Max Hits": "1",
      "TP Cost": "8",
      "Requirements": "Lilium Orb: Orb 1 Node 3",
      "Description": "increases own physical attack power by 30% for 10 secondsaction speed increases after 200 useseffect increases by 10% after 400 usesincreases own physical defense for 10 seconds after 400 uses and the Second Artes skill is equipped"
    },
    "palm strike": {
      "Arte Name": "Palm Strike",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Stun",
      "Damage Spread": "3.00 x 1",
      "Total Damage (%)": "300",
      "Max Hits": "1",
      "TP Cost": "7",
      "Requirements": "Lilium Orb: Orb 1 Node 5",
      "Description": "attack speed increases after 100 uses30% chance to inflict Stun on enemies damaged by this attack after 200 uses"
    },
    "aqua sweep": {
      "Arte Name": "Aqua Sweep",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "Water",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Weak",
      "Damage Spread": "0.80 x 3",
      "Total Damage (%)": "240",
      "Max Hits": "3",
      "TP Cost": "16",
      "Requirements": "Lilium Orb: Orb 1 Node 4",
      "Description": "knockdown enabled against enemies that can be trippedarea of effect increases after 200 uses"
    },
    "swallow dance": {
      "Arte Name": "Swallow Dance",
      "Enabled Effects": "Stand Up, Aerial",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "1.65 x 2+ 1.65 x 1",
      "Total Damage (%)": "330[*495]",
      "Max Hits": "2[*3]",
      "TP Cost": "10",
      "Requirements": "Lilium Orb: Orb 1 Node 2",
      "Description": "max hit count increases by one if the Second Artes 2 skill is equippedJude becomes airborne after executing this arteattack speed increases after 200 usesforces downed enemies to stand after 400 uses"
    },
    "talon storm": {
      "Arte Name": "Talon Storm",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "-",
      "Damage Spread": "0.84 x 5",
      "Total Damage (%)": "420",
      "Max Hits": "5",
      "TP Cost": "14",
      "Requirements": "Lilium Orb: Orb 1 Node 5",
      "Description": "attack speed increases after 200 uses"
    },
    "cyclonic surge": {
      "Arte Name": "Cyclonic Surge",
      "Enabled Effects": "Aerial",
      "Elemental Attributes": "Wind",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Paralysis",
      "Damage Spread": "1.00 x 3",
      "Total Damage (%)": "300",
      "Max Hits": "3",
      "TP Cost": "16",
      "Requirements": "Lilium Orb: Orb 2 Node 5",
      "Description": "chance to inflict Paralysis increases after 200 usesJude becomes airborne after executing this arte"
    },
    "beast": {
      "Arte Name": "Beast",
      "Enabled Effects": "Knockdown, Aerial, Guard Break",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Vitality",
      "Damage Effect": "-",
      "Damage Spread": "4.00 x 1",
      "Total Damage (%)": "400",
      "Max Hits": "1",
      "TP Cost": "14",
      "Requirements": "Lilium Orb: Orb 1 Node 8",
      "Description": "chance to Guard Break the enemy after 200 useschance to break enemy's Iron Stance effect increases after 200 uses"
    },
    "whirlwind snap": {
      "Arte Name": "Whirlwind Snap",
      "Enabled Effects": "Aerial",
      "Elemental Attributes": "Wind",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Paralysis",
      "Damage Spread": "2.50 x 1",
      "Total Damage (%)": "250",
      "Max Hits": "1",
      "TP Cost": "12",
      "Requirements": "Lilium Orb: Orb 2 Node 1",
      "Description": "enemies hit by this attack are pulled towards Judedistance pulled increases after 200 and 400 uses"
    },
    "rising falcon": {
      "Arte Name": "Rising Falcon",
      "Enabled Effects": "Aerial",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "3.50 x 1+ 0.70 x 1",
      "Total Damage (%)": "350[*420]",
      "Max Hits": "1[*2]",
      "TP Cost": "15",
      "Requirements": "Lilium Orb: Orb 1 Node 6",
      "Description": "adds an additional hit when activated from the ground after 200 uses"
    },
    "soaring vortex": {
      "Arte Name": "Soaring Vortex",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "Wind",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Paralysis",
      "Damage Spread": "3.80 x 1",
      "Total Damage (%)": "380",
      "Max Hits": "1",
      "TP Cost": "12",
      "Requirements": "Lilium Orb: Orb 1 Node 1",
      "Description": "this arte will not activate unless an enemy that is not knocked down is within rangeignores enemy Guard action and Iron Stance effectarea of effect increases after 200 uses"
    },
    "mirage blitz": {
      "Arte Name": "Mirage Blitz",
      "Enabled Effects": "Aerial",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Stun",
      "Damage Spread": "2.50 x 1+ 0.50 x 1[*0.00]",
      "Total Damage (%)": "250/300[*0]",
      "Max Hits": "1/2",
      "TP Cost": "9",
      "Requirements": "Lilium Orb: Orb 2 Node 3",
      "Description": "chance to inflict Stun on enemies damaged by this attack after 200 useschance to break enemy's Iron Stance effect increases after 200 usesattack speed increases after 400 usesthe backstep motion will deal damage after 400 usesdeals no damage if activated midair"
    },
    "raging blast": {
      "Arte Name": "Raging Blast",
      "Enabled Effects": "Stand Up, Knockdown",
      "Elemental Attributes": "Fire",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Burn",
      "Damage Spread": "1.50 x 13.00 x 1",
      "Total Damage (%)": "450",
      "Max Hits": "2",
      "TP Cost": "18",
      "Requirements": "Lilium Orb: Orb 2 Node 4",
      "Description": "chance to inflict Burn increases after 100, 200, and 400 usesforces downed enemies to stand, then returns them to a downed state"
    },
    "dragon shot": {
      "Arte Name": "Dragon Shot",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "1.05 x 12.45 x 1+ 1.05 x 1",
      "Total Damage (%)": "350/455",
      "Max Hits": "2/3",
      "TP Cost": "18",
      "Requirements": "Lilium Orb: Orb 2 Node 1",
      "Description": "Jude becomes airborne after executing this arteadds an additional hit after 200 uses"
    },
    "sun spark": {
      "Arte Name": "Sun Spark",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "Light",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "4.50 x 1[*5.40 x 1]",
      "Total Damage (%)": "450/540",
      "Max Hits": "1",
      "TP Cost": "20",
      "Requirements": "Lilium Orb: Orb 1 Node 6",
      "Description": "range and damage increase after 200 uses"
    },
    "phoenix plunge": {
      "Arte Name": "Phoenix Plunge",
      "Enabled Effects": "Knockdown, Aerial",
      "Elemental Attributes": "Fire",
      "Sub-Status Attributes": "Intelligence",
      "Damage Effect": "Burn",
      "Damage Spread": "2.00 x 13.00 x 1",
      "Total Damage (%)": "500",
      "Max Hits": "2",
      "TP Cost": "18",
      "Requirements": "Lilium Orb: Orb 2 Node 5",
      "Description": "Jude becomes airborne after executing this arteknockback effect is reduced after 200 usesknocks enemies higher upwards after 200 uses"
    },
    "blunt fang": {
      "Arte Name": "Blunt Fang",
      "Enabled Effects": "-",
      "Elemental Attributes": "Dark",
      "Sub-Status Attributes": "Dexterity",
      "Damage Effect": "Terror",
      "Damage Spread": "2.00 x 1",
      "Total Damage (%)": "200",
      "Max Hits": "1",
      "TP Cost": "17",
      "Requirements": "Event: acquire the Arte Tome: \"One-Hit Kill\" valuable after completing the \"The Lost Transcendental Ring\" sub-event",
      "Description": "chance to inflict Instant Death on a downed enemychance increases by 5% after 100, 200, and 400 uses"
    },
    "muzet": {
      "Arte Name": "Muzét",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "Fire, Water, Wind, Earth",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Burn, Weak, Slow, Paralysis",
      "Damage Spread": "?",
      "Total Damage (%)": "1000",
      "Max Hits": "7",
      "TP Cost": "30",
      "Requirements": "available only while Muzét is tethered to Jude",
      "Description": "first hit forces downed enemies to stand"
    },
    "immaculate healer": {
      "Arte Name": "Immaculate Healer",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Psyche",
      "Damage Effect": "-",
      "Damage Spread": "-",
      "Total Damage (%)": "-",
      "Max Hits": "-",
      "TP Cost": "5",
      "Requirements": "the Second Artes skill must be equippedreplaces Healer by holding the Artes button",
      "Description": "heals between 36% and 18% of max HP at a rate of 12% to 6% HP per burst depending on the distance from Jude"
    },
    "double demon fist": {
      "Arte Name": "Double Demon Fist",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "0.85 x 1",
      "Total Damage (%)": "85",
      "Max Hits": "1",
      "TP Cost": "0",
      "Requirements": "the Second Artes skill must be equippedextends from Demon Fist by holding the Artes button",
      "Description": "-"
    },
    "cerberus blast": {
      "Arte Name": "Cerberus Blast",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "-",
      "Damage Spread": "1.50 x 1",
      "Total Damage (%)": "150",
      "Max Hits": "1",
      "TP Cost": "0",
      "Requirements": "the Second Artes skill must be equippedextends from Cerberus Strike by holding the Artes button",
      "Description": "-"
    },
    "coil": {
      "Arte Name": "Coil",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "2.00 x 1",
      "Total Damage (%)": "200",
      "Max Hits": "1",
      "TP Cost": "8",
      "Requirements": "the Second Artes skill must be equippedreplaces Steel by holding the Artes button",
      "Description": "increases physical attack power and defense by 30% temporarily"
    },
    "reaper's toll": {
      "Arte Name": "Reaper's Toll",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "-",
      "Damage Spread": "3.00 x 1",
      "Total Damage (%)": "300",
      "Max Hits": "1",
      "TP Cost": "7",
      "Requirements": "the Second Artes 2 skill must be equippedchains after Palm Strike by using it twice consecutively",
      "Description": "-"
    },
    "wind blade (demon fist)": {
      "Arte Name": "Wind Blade",
      "Enabled Effects": "-",
      "Elemental Attributes": "Wind",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Paralysis",
      "Damage Spread": "0.38 x 1\n1.66 x 1",
      "Total Damage (%)": "204",
      "Max Hits": "2",
      "TP Cost": "6",
      "Requirements": "- the Milla Sync skill must be equipped\n- replaces Demon Fist while linked with Milla Maxwell",
      "Description": "-"
    },
    "wind blade (double demon fist)": {
      "Arte Name": "Wind Blade",
      "Enabled Effects": "-",
      "Elemental Attributes": "Wind",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Paralysis",
      "Damage Spread": "0.34 x 1\n0.85 x 1",
      "Total Damage (%)": "119",
      "Max Hits": "2",
      "TP Cost": "0",
      "Requirements": "- the Milla Sync skill must be equipped\n- replaces Double Demon Fist while linked with Milla Maxwell",
      "Description": "-"
    },
    "grave (cerberus strike)": {
      "Arte Name": "Grave",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "Earth",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Slow",
      "Damage Spread": "1.00 x 2\n2.80 x 1",
      "Total Damage (%)": "480",
      "Max Hits": "3",
      "TP Cost": "9",
      "Requirements": "- the Milla Sync skill must be equipped\n- replaces Cerberus Strike Fist while linked with Milla Maxwell",
      "Description": "Third and fourth hits force downed enemies to stand"
    },
    "grave (cerberus blast)": {
      "Arte Name": "Grave",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "Earth",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Slow",
      "Damage Spread": "3.00 x 1",
      "Total Damage (%)": "300",
      "Max Hits": "1",
      "TP Cost": "0",
      "Requirements": "- the Milla Sync skill must be equipped\n- replaces Cerberus Blast Fist while linked with Milla Maxwell",
      "Description": "Third and fourth hits force downed enemies to stand"
    },
    "aqua Protection (steel)": {
      "Arte Name": "Aqua Protection",
      "Enabled Effects": "-",
      "Elemental Attributes": "Water",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Weak",
      "Damage Spread": "2.00 x 6",
      "Total Damage (%)": "1200",
      "Max Hits": "6",
      "TP Cost": "8",
      "Requirements": "- the Milla Sync skill must be equipped\n- replaces Steel while linked with Milla Maxwell",
      "Description": "summons three orbs at once when activated from Coil"
    },
    "aqua Protection (soil)": {
      "Arte Name": "Aqua Protection",
      "Enabled Effects": "-",
      "Elemental Attributes": "Water",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Weak",
      "Damage Spread": "2.00 x 6",
      "Total Damage (%)": "1200",
      "Max Hits": "6",
      "TP Cost": "8",
      "Requirements": "- the Milla Sync skill must be equipped\n- replaces Coil while linked with Milla Maxwell",
      "Description": "summons three orbs at once when activated from Coil"
    },
    "flare bomb (palm Strike)": {
      "Arte Name": "Flare bomb",
      "Enabled Effects": "-",
      "Elemental Attributes": "Fire",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Burn",
      "Damage Spread": "0.90 x 1",
      "Total Damage (%)": "90",
      "Max Hits": "1",
      "TP Cost": "7",
      "Requirements": "- the Milla Sync skill must be equipped\n- replaces Palm Strike linked with Milla Maxwell",
      "Description": "-"
    },
    "flare bomb (reaper's tool)": {
      "Arte Name": "Flare bomb",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "Fire",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Burn",
      "Damage Spread": "2.10 x 1",
      "Total Damage (%)": "210",
      "Max Hits": "1",
      "TP Cost": "7",
      "Requirements": "- the Milla Sync skill must be equipped\n- replaces Reaper's Toll linked with Milla Maxwell",
      "Description": "-"
    },
    "savage roar": {
      "Arte Name": "Savage Roar",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "4.00 x 12.00 x 4",
      "Total Damage (%)": "1200",
      "Max Hits": "5",
      "TP Cost": "30",
      "Requirements": "Lilium Orb: Orb 2 Node 2",
      "Description": "-"
    },
    "shattering demon fist": {
      "Arte Name": "Shattering Demon Fist",
      "Enabled Effects": "Stand Up, Knockdown",
      "Elemental Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "7.50 x 1",
      "Total Damage (%)": "750",
      "Max Hits": "1",
      "TP Cost": "30",
      "Requirements": "Event: acquire the Arte Tome: \"Tremorous Fist\" valuable after completing the game",
      "Description": "-"
    },
    "final fury": {
      "Arte Name": "Final Fury",
      "Elemental Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "4500",
      "Max Hits": "13",
      "Requirements": "Over Limit mode must be active\n- activated by using Savage Roar and holding the Attack button",
      "Description": "-",
      "Enabled Effects": "-"
    },
    "tiger blade sigma": {
      "Arte Name": "Tiger Blade Sigma",
      "Elemental Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "4800",
      "Max Hits": "7",
      "Requirements": "available if a clear save file exists on the player's profile\nJude Mathis must be linked with Milla Maxwell\nOver Limit mode must be active\nactivated by using Shattering Demon Fist and holding the Attack button",
      "Description": "-",
      "Enabled Effects": "-"
    }
  },
  "alvin": {
    "demon fang": {
      "Arte Name": "Demon Fang",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "2",
      "TP Cost": "6",
      "Requirements": "Lilium Orb: Orb 1 Node 1",
      "Description": "the projectile penetrates targets after 400 uses\nforces downed enemies to stand after 400 uses"
    },
    "tiger blade": {
      "Arte Name": "Tiger Blade",
      "Enabled Effects": "Aerial",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "2",
      "TP Cost": "9",
      "Requirements": "Lilium Orb: Orb 1 Node 1",
      "Description": "attack speed increases after 200 uses"
    },
    "sonic thrust": {
      "Arte Name": "Sonic Thrust",
      "Enabled Effects": "Aerial",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "1",
      "TP Cost": "8",
      "Requirements": "Lilium Orb: Orb 1 Node 3",
      "Description": "aerial-enabled after 100 uses"
    },
    "variable trigger": {
      "Arte Name": "Variable Trigger",
      "Enabled Effects": "-",
      "Elemental Attributes": "Fire",
      "Sub-Status Attributes": "Dexterity",
      "Damage Effect": "Burn",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "1",
      "TP Cost": "10",
      "Requirements": "Lilium Orb: Orb 2 Node 1",
      "Description": "-"
    },
    "tornado drive": {
      "Arte Name": "Tornado Drive",
      "Enabled Effects": "Aerial",
      "Elemental Attributes": "Light",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "2",
      "TP Cost": "12",
      "Requirements": "Lilium Orb: Orb 1 Node 6",
      "Description": "-"
    },
    "arc fire": {
      "Arte Name": "Arc Fire",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "Fire",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Burn",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "3",
      "TP Cost": "10",
      "Requirements": "Lilium Orb: Orb 1 Node 4",
      "Description": "forces downed enemies to stand after 200 uses"
    },
    "guardian field": {
      "Arte Name": "Guardian Field",
      "Enabled Effects": "-",
      "Elemental Attributes": "Light",
      "Sub-Status Attributes": "Psyche",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "4",
      "TP Cost": "15",
      "Requirements": "Lilium Orb: Orb 1 Node 2",
      "Description": "heals up to 15% of max HP at a rate of 5% HP per burst\nheals up to 24% of max HP at a rate of 8% HP per burst after 400 uses"
    },
    "punishing shot": {
      "Arte Name": "Punishing Shot",
      "Enabled Effects": "-",
      "Elemental Attributes": "Wind",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Paralysis",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "3/4",
      "TP Cost": "14",
      "Requirements": "Lilium Orb: Orb 1 Node 6",
      "Description": "adds an additional hit after 200 uses"
    },
    "moonlight cleft": {
      "Arte Name": "Moonlight Cleft",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "2",
      "TP Cost": "16",
      "Requirements": "Lilium Orb: Orb 2 Node 4",
      "Description": "-"
    },
    "squall shot": {
      "Arte Name": "Squall Shot",
      "Enabled Effects": "-",
      "Elemental Attributes": "Water",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Weak",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "1~24",
      "TP Cost": "17",
      "Requirements": "Lilium Orb: Orb 1 Node 8",
      "Description": "-"
    },
    "terra rupture": {
      "Arte Name": "Terra Rupture",
      "Enabled Effects": "-",
      "Elemental Attributes": "Earth",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Slow",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "2",
      "TP Cost": "13",
      "Requirements": "Lilium Orb: Orb 1 Node 5",
      "Description": "pulls enemies towards Alvin after 200 uses"
    },
    "homing shot": {
      "Arte Name": "Homing Shot",
      "Enabled Effects": "Aerial",
      "Elemental Attributes": "Dark",
      "Sub-Status Attributes": "Dexterity",
      "Damage Effect": "Terror",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "1",
      "TP Cost": "12",
      "Requirements": "Lilium Orb: Orb 2 Node 3",
      "Description": "Alvin becomes airborne after executing this attack"
    },
    "dragon swarm": {
      "Arte Name": "Dragon Swarm",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "5",
      "TP Cost": "20",
      "Requirements": "Lilium Orb: Orb 2 Node 1",
      "Description": "attack speed increases after 200 uses"
    },
    "pulse shot": {
      "Arte Name": "Pulse Shot",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "5",
      "TP Cost": "18",
      "Requirements": "Lilium Orb: Orb 1 Node 5",
      "Description": "forces downed enemies to stand after 200 uses"
    },
    "dark radiance": {
      "Arte Name": "Dark Radiance",
      "Enabled Effects": "Knockdown, Aerial",
      "Elemental Attributes": "Fire",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Burn",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "2",
      "TP Cost": "24",
      "Requirements": "Lilium Orb: Orb 2 Node 5",
      "Description": "aerial-enabled after 100 uses"
    },
    "demon inferno": {
      "Arte Name": "Demon Inferno",
      "Enabled Effects": "-",
      "Elemental Attributes": "Fire",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Burn",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "3",
      "TP Cost": "26",
      "Requirements": "Lilium Orb: Orb 2 Node 5",
      "Description": "-"
    },
    "cross cleave": {
      "Arte Name": "Cross Cleave",
      "Enabled Effects": "-",
      "Elemental Attributes": "Dark",
      "Sub-Status Attributes": "Intelligence",
      "Damage Effect": "Terror",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "4/5/6",
      "TP Cost": "28",
      "Requirements": "Lilium Orb: Orb 2 Node 5",
      "Description": "adds an additional hit after 200 and 400 uses"
    },
    "fierce demon fang": {
      "Arte Name": "Fierce Demon Fang",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "1",
      "TP Cost": "6",
      "Requirements": "Charge: Demon Fang",
      "Description": "area of effect increases after 400 uses of Demon Fang"
    },
    "tiger rage": {
      "Arte Name": "Tiger Rage",
      "Enabled Effects": "Aerial",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "3",
      "TP Cost": "9",
      "Requirements": "Charge: Tiger Blade",
      "Description": "-"
    },
    "sonic barrage": {
      "Arte Name": "Sonic Barrage",
      "Enabled Effects": "Stand Up, Knockdown",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "2",
      "TP Cost": "8",
      "Requirements": "Charge: Sonic Thrust",
      "Description": "forces downed enemies to stand, then returns them to a downed state"
    },
    "variable blast": {
      "Arte Name": "Variable Blast",
      "Enabled Effects": "-",
      "Elemental Attributes": "Fire",
      "Sub-Status Attributes": "Dexterity",
      "Damage Effect": "Burn",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "1",
      "TP Cost": "10",
      "Requirements": "Charge: Variable Trigger",
      "Description": "projectile penetrates targets"
    },
    "cyclone drive": {
      "Arte Name": "Cyclone Drive",
      "Enabled Effects": "Aerial",
      "Elemental Attributes": "Light",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "4",
      "TP Cost": "12",
      "Requirements": "Charge: Tornado Drive",
      "Description": "-"
    },
    "arc blaze": {
      "Arte Name": "Arc Blaze",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "Fire",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Burn",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "3",
      "TP Cost": "10",
      "Requirements": "Charge: Arc Fire",
      "Description": "forces downed enemies to stand after 200 uses of Arc Fire"
    },
    "guardian grove": {
      "Arte Name": "Guardian Grove",
      "Enabled Effects": "-",
      "Elemental Attributes": "Light",
      "Sub-Status Attributes": "Psyche",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "?",
      "TP Cost": "15",
      "Requirements": "Charge: Guardian Field",
      "Description": "heals 15% of max HP at a rate of 5% HP per burst\nheals up to 24% of max HP at a rate of 8% HP per burst after 400 uses of Guardian Field\nmovement is available before the healing glyph disappears\nattack speed increases after 200 uses of Guardian Field"
    },
    "punishing beam": {
      "Arte Name": "Punishing Beam",
      "Enabled Effects": "Stand Up, Knockdown",
      "Elemental Attributes": "Wind",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Paralysis",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "3",
      "TP Cost": "14",
      "Requirements": "Charge: Punishing Shot",
      "Description": "forces downed enemies to stand with the first hit after 200 uses of Punishing Shot\nfinal hit still knocks down enemies"
    },
    "twin moonlight cleft": {
      "Arte Name": "Twin Moonlight Cleft",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "4",
      "TP Cost": "16",
      "Requirements": "Charge: Moonlight Cleft",
      "Description": "-"
    },
    "storm shot": {
      "Arte Name": "Storm Shot",
      "Enabled Effects": "-",
      "Elemental Attributes": "Water",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Weak",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "1~6+",
      "TP Cost": "17",
      "Requirements": "Charge: Squall Shot",
      "Description": "-"
    },
    "terra fissure": {
      "Arte Name": "Terra Fissure",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "Earth",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Slow",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "3",
      "TP Cost": "13",
      "Requirements": "Charge: Terra Rupture",
      "Description": "-"
    },
    "homing cannon": {
      "Arte Name": "Homing Cannon",
      "Enabled Effects": "Aerial",
      "Elemental Attributes": "Dark",
      "Sub-Status Attributes": "Dexterity",
      "Damage Effect": "Terror",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "3",
      "TP Cost": "12",
      "Requirements": "Charge: Homing Shot",
      "Description": "Alvin becomes airborne after executing this attack"
    },
    "dragon salvo": {
      "Arte Name": "Dragon Salvo",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "6",
      "TP Cost": "20",
      "Requirements": "Charge: Dragon Swarm",
      "Description": "-"
    },
    "sweeping shot": {
      "Arte Name": "Sweeping Shot",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "5",
      "TP Cost": "18",
      "Requirements": "Charge: Pulse Shot",
      "Description": "forces downed enemies to stand after 200 uses of Pulse Shot"
    },
    "devil flare": {
      "Arte Name": "Devil Flare",
      "Enabled Effects": "Knockdown, Aerial",
      "Elemental Attributes": "Fire",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Burn",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "2",
      "TP Cost": "24",
      "Requirements": "Charge: Dark Radiance",
      "Description": "aerial-enabled after 100 uses of Dark Radiance"
    },
    "abyssal inferno": {
      "Arte Name": "Abyssal Inferno",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "Fire",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Burn",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "3",
      "TP Cost": "26",
      "Requirements": "Charge: Demon Inferno",
      "Description": "-"
    },
    "muzzle roar": {
      "Arte Name": "Muzzle Roar",
      "Enabled Effects": "-",
      "Elemental Attributes": "Dark",
      "Sub-Status Attributes": "Intelligence",
      "Damage Effect": "Terror",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "6/7/8",
      "TP Cost": "28",
      "Requirements": "Charge: Cross Cleave",
      "Description": "adds an additional hit after 200 and 400 uses of Cross Cleave"
    },
    "hell fryer": {
      "Arte Name": "Hell Fryer",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "Fire",
      "Damage Effect": "Burn",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "2",
      "TP Cost": "30",
      "Requirements": "Lilium Orb: Orb 2 Node 2",
      "Description": "attacks faster while the Charge ability is active\nAlvin becomes airborne after executing this attack"
    },
    "terminus pride": {
      "Arte Name": "Terminus Pride",
      "Elemental Attributes": "Fire",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "8",
      "Requirements": "Over Limit mode must be active\nactivated by using Hell Fryer and holding the Attack button",
      "Description": "grants one additional stacked charge",
      "Enabled Effects": "-"
    }
  },
  "rowen": {
    "severed fate": {
      "Arte Name": "Severed Fate",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Dexterity",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "3",
      "TP Cost": "7",
      "Requirements": "Lilium Orb: Orb 1 Node 2",
      "Description": "hold down the Artes button to lower the delay between the knives being thrown and falling back down\narea of effect increases after 100 uses"
    },
    "marche waltz": {
      "Arte Name": "Marche Waltz",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "Light",
      "Sub-Status Attributes": "Dexterity",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "2",
      "TP Cost": "9",
      "Requirements": "Lilium Orb: Orb 1 Node 4",
      "Description": "forces downed enemies to stand after 100 uses"
    },
    "meteoric waltz": {
      "Arte Name": "Meteoric Waltz",
      "Enabled Effects": "Aerial",
      "Elemental Attributes": "Earth",
      "Sub-Status Attributes": "Dexterity",
      "Damage Effect": "Slow",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "1/4/5",
      "TP Cost": "11",
      "Requirements": "Lilium Orb: Orb 1 Node 6",
      "Description": "marks the ground with a magic glyphs that erupt with an earth spike when an enemy steps on it\naerial-enabled after 100 uses\nprojectiles increase by three at 200 uses, and by one at 400 uses"
    },
    "spectral purge": {
      "Arte Name": "Spectral Purge",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "Water",
      "Sub-Status Attributes": "Dexterity",
      "Damage Effect": "Weak",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "4",
      "TP Cost": "13",
      "Requirements": "Lilium Orb: Orb 2 Node 1",
      "Description": "marks an enemy or the area in front of Rowen with a glyph that explodes after a few seconds\nonly the explosion is capable of knockdown"
    },
    "fireball": {
      "Arte Name": "Fireball",
      "Enabled Effects": "-",
      "Elemental Attributes": "Fire",
      "Damage Effect": "Burn",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "1[*2~4]",
      "Casting Time (seconds)": "1.00",
      "TP Cost": "9",
      "Requirements": "Lilium Orb: Orb 1 Node 3",
      "Description": "press the Artes button while Arte Tuning is active to rapidly shoot up to three more fireballs"
    },
    "wind lance": {
      "Arte Name": "Wind Lance",
      "Enabled Effects": "-",
      "Elemental Attributes": "Wind",
      "Damage Effect": "Paralysis",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "1",
      "Casting Time (seconds)": "1.00",
      "TP Cost": "10",
      "Requirements": "Lilium Orb: Orb 1 Node 5",
      "Description": "press the Artes button while Arte Tuning is active to shoot one bolt per target in front of Rowen simultaneously"
    },
    "rock trine": {
      "Arte Name": "Rock Trine",
      "Enabled Effects": "-",
      "Elemental Attributes": "Earth",
      "Damage Effect": "Slow",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "3[*5]",
      "Casting Time (seconds)": "1.00",
      "TP Cost": "9",
      "Requirements": "Lilium Orb: Orb 1 Node 1",
      "Description": "press the Artes button while Arte Tuning is active to hit the target again with more rocks"
    },
    "splash": {
      "Arte Name": "Splash",
      "Enabled Effects": "-",
      "Elemental Attributes": "Water",
      "Damage Effect": "Weak",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "6",
      "Casting Time (seconds)": "1.00",
      "TP Cost": "12",
      "Requirements": "Lilium Orb: Orb 1 Node 1",
      "Description": "move the left control stick while Arte Tuning is active to control the flow of water"
    },
    "air pressure": {
      "Arte Name": "Air Pressure",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "Earth",
      "Damage Effect": "Slow",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "3[*4]",
      "Casting Time (seconds)": "2.00",
      "TP Cost": "22",
      "Requirements": "Lilium Orb: Orb 1 Node 5",
      "Description": "press the Artes button while Arte Tuning is active to add more pressure adds one final hit that causes knockdown"
    },
    "blue sphere": {
      "Arte Name": "Blue Sphere",
      "Enabled Effects": "-",
      "Elemental Attributes": "Water",
      "Damage Effect": "Slow",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "1",
      "Casting Time (seconds)": "2.00",
      "TP Cost": "24",
      "Requirements": "Lilium Orb: Orb 1 Node 6",
      "Description": "press and hold the Attack button while Arte Tuning is active to increase the range of the spell"
    },
    "freeze lancer": {
      "Arte Name": "Freeze Lancer",
      "Enabled Effects": "-",
      "Elemental Attributes": "Water, Earth",
      "Damage Effect": "Weak, Slow",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "10[*10~16]",
      "Casting Time (seconds)": "2.00",
      "TP Cost": "24",
      "Requirements": "Lilium Orb: Orb 2 Node 3",
      "Description": "press the Artes button while Arte Tuning is active to increase the number of hits"
    },
    "shimmering toll": {
      "Arte Name": "Shimmering Toll",
      "Enabled Effects": "-",
      "Elemental Attributes": "Light",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "4[*6]",
      "Casting Time (seconds)": "2.10",
      "TP Cost": "23",
      "Requirements": "Lilium Orb: Orb 1 Node 8",
      "Description": "rotate the left control stick while Arte Tuning is active to increase the number of hits"
    },
    "tightening chains": {
      "Arte Name": "Tightening Chains",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "2~5[*3~6]",
      "Casting Time (seconds)": "2.00",
      "TP Cost": "28",
      "Requirements": "Lilium Orb: Orb 2 Node 1",
      "Description": "use the left control stick while Arte Tuning is active to add an extra hit aimed toward the input\n            direction"
    },
    "roche Waltz": {
      "Arte Name": "Roche Waltz",
      "Enabled Effects": "-",
      "Elemental Attributes": "Earth",
      "Damage Effect": "Slow",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "1~19",
      "Casting Time (seconds)": "3.00",
      "TP Cost": "14",
      "Requirements": "Lilium Orb: Orb 2 Node 5",
      "Description": "use the left control stick while Arte Tuning is active to control the movement of the spell"
    },
    "diffusional drive": {
      "Arte Name": "Diffusional Drive",
      "Enabled Effects": "-",
      "Elemental Attributes": "Water",
      "Damage Effect": "Weak",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "12~16",
      "Casting Time (seconds)": "3.00",
      "TP Cost": "36",
      "Requirements": "Lilium Orb: Orb 2 Node 5",
      "Description": "use the left control stick while Arte Tuning is active to control the center of the spell\n          heals 8-10% of max HP to all allies"
    },
    "glacial core": {
      "Arte Name": "Glacial core",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "Water, Earth",
      "Damage Effect": "Weak, Slow",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "5",
      "Casting Time (seconds)": "3.30",
      "TP Cost": "33",
      "Requirements": "Lilium Orb: Orb 2 Node 5",
      "Description": "use the left control stick while Arte Tuning is active to control the movement of the spell"
    },
    "divine streak": {
      "Arte Name": "Divine Streak",
      "Enabled Effects": "-",
      "Elemental Attributes": "Light",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "10",
      "Casting Time (seconds)": "3.50",
      "TP Cost": "38",
      "Requirements": "Lilium Orb: Orb 2 Node 4",
      "Description": "use the left control stick while Arte Tuning is active to control the direction of the spell"
    },
    "tidal wave": {
      "Arte Name": "Tidal Wave",
      "Enabled Effects": "-",
      "Elemental Attributes": "Water",
      "Damage Effect": "Weak",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "8",
      "Casting Time (seconds)": "3.00",
      "TP Cost": "40",
      "Requirements": "Lilium Orb: Orb 2 Node 2",
      "Description": "-"
    },
    "grand finale": {
      "Arte Name": "Grand Finale",
      "Elemental Attributes": "Water, Earth",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "2",
      "Requirements": "Over Limit mode must be active\nactivated by using Tidal Wave and holding the Attack button",
      "Description": "-",
    },
  },
  "elize": {
    "pow hammer": {
      "Arte Name": "Pow Hammer",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Stun",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "1",
      "TP Cost": "5",
      "Requirements": "Lilium Orb: Orb 1 Node 1",
      "Description": "chance to inflict Stun increases while Teepo OFF is active\nchance to inflict Stun increases after 100 uses"
    },
    "teepo spray": {
      "Arte Name": "Teepo Spray",
      "Enabled Effects": "-",
      "Elemental Attributes": "Dark",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Terror",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "1[*2]",
      "TP Cost": "7",
      "Requirements": "Lilium Orb: Orb 1 Node 2",
      "Description": "while Teepo OFF is active\nrange and projectile speed decrease, and projectile size increases\nadds an additional hit after 200 uses\nwhile Teepo ON is active, projectile speed and range increases after 100 uses"
    },
    "teepo quake": {
      "Arte Name": "Teepo Quake",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "Earth",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Slow",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "2/3[*3/4]",
      "TP Cost": "10",
      "Requirements": "Lilium Orb: Orb 2 Node 1",
      "Description": "max hits is increased while Teepo OFF is active\nadds an additional hit after 200 uses\nforces downed enemies to stand after 200 uses"
    },
    "teepo roar": {
      "Arte Name": "Teepo Roar",
      "Enabled Effects": "Knockdown, Guard Break",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Vitality",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "1",
      "TP Cost": "12",
      "Requirements": "Lilium Orb: Orb 1 Node 8",
      "Description": "attack range and knock-back distance increases while Teepo OFF is active\nchance to guard break is available after 100 uses"
    },
    "teepo copter": {
      "Arte Name": "Teepo Copter",
      "Enabled Effects": "-",
      "Elemental Attributes": "Wind",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Paralysis",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "4[*8]",
      "TP Cost": "16",
      "Requirements": "Lilium Orb: Orb 1 Node 5",
      "Description": "max hits and flight duration is increased while Teepo OFF is active\nprecision in chasing enemies increases after 400 and 1000 uses"
    },
    "teepo squash": {
      "Arte Name": "Teepo Squash",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "1",
      "TP Cost": "12",
      "Requirements": "Lilium Orb: Orb 2 Node 1",
      "Description": "area of effect increases while Teepo OFF is active\narea of effect increases after 100 and 200 uses"
    },
    "teepo vacuum": {
      "Arte Name": "Teepo Vacuum",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "Dark",
      "Sub-Status Attributes": "Dexterity",
      "Damage Effect": "Terror",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "3[*5]",
      "TP Cost": "36",
      "Requirements": "Lilium Orb: Orb 2 Node 5",
      "Description": "max hits is increased while Teepo OFF is active\ncan only damage light-weight class monsters\nmid-weight monsters class can be swallowed after 100 uses\nheavy-weight monsters class can be swallowed after 400 uses\nsuper-heavy-weight monsters class can be swallowed after 1000 uses"
    },
    "pixie circle": {
      "Arte Name": "Pixie Circle",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "-",
      "Total Damage (%)": "-",
      "Max Hits": "-",
      "Casting Time (seconds)": "2.00",
      "TP Cost": "12",
      "Requirements": "Lilium Orb: Orb 1 Node 1",
      "Description": "heals 10% of max HP to all allies within a small area\n healing increases to 20% of max HP and range increases while Teepo ON is active"
    },
    "recover": {
      "Arte Name": "Recover",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "-",
      "Total Damage (%)": "-",
      "Max Hits": "-",
      "Casting Time (seconds)": "1.00",
      "TP Cost": "10",
      "Requirements": "Lilium Orb: Orb 1 Node 1",
      "Description": "cures all negative status ailments for one ally"
    },
    "healing circle": {
      "Arte Name": "Healing Circle",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "-",
      "Total Damage (%)": "-",
      "Max Hits": "-",
      "Casting Time (seconds)": "3.00",
      "TP Cost": "24",
      "Requirements": "Lilium Orb: Orb 1 Node 4",
      "Description": "heals up to 40% of max HP at a rate of 10% per burst to all allies within a moderate area\nhealing increases to 50% of max HP at the same rate while Teepo ON is active"
    },
    "dispel": {
      "Arte Name": "Dispel",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "-",
      "Total Damage (%)": "-",
      "Max Hits": "-",
      "Casting Time (seconds)": "2.00",
      "TP Cost": "22",
      "Requirements": "Lilium Orb: Orb 1 Node 6",
      "Description": "cures all negative status ailments for all allies\nprovides an effect that prevents negative status ailments temporarily while Teepo ON is active"
    },
    "resurrection": {
      "Arte Name": "Resurrection",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "-",
      "Total Damage (%)": "-",
      "Max Hits": "-",
      "Casting Time (seconds)": "3.00",
      "TP Cost": "26",
      "Requirements": "Lilium Orb: Orb 1 Node 6",
      "Description": "heals 50% of max HP to one ally\nif the ally is knocked out, revives that ally with 50% of max HP healed"
    },
    "negative gate": {
      "Arte Name": "Negative Gate",
      "Enabled Effects": "-",
      "Elemental Attributes": "Dark",
      "Damage Effect": "Terror",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "8",
      "Casting Time (seconds)": "2.50",
      "TP Cost": "24",
      "Requirements": "Lilium Orb: Orb 1 Node 5",
      "Description": "pulls enemies towards the center of this spell\npulling power is increased while Teepo ON is active"
    },
    "nurse": {
      "Arte Name": "Nurse",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "-",
      "Total Damage (%)": "-",
      "Max Hits": "-",
      "Casting Time (seconds)": "4.00",
      "TP Cost": "36",
      "Requirements": "Lilium Orb: Orb 2 Node 4",
      "Description": "heals 50% of max HP to all allies\nhealing increases to 60% of max HP while Teepo ON is active"
    },
    "revive": {
      "Arte Name": "Revive",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "-",
      "Total Damage (%)": "-",
      "Max Hits": "-",
      "Casting Time (seconds)": "4.00",
      "TP Cost": "50",
      "Requirements": "Lilium Orb: Orb 2 Node 5",
      "Description": "automatically revives the affected ally upon being knocked out\neffect not shared by linked allies"
    },
    "dark visitor": {
      "Arte Name": "Dark Visitor",
      "Enabled Effects": "-",
      "Elemental Attributes": "Dark",
      "Damage Effect": "Terror",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "6",
      "Casting Time (seconds)": "3.00",
      "TP Cost": "32",
      "Requirements": "Lilium Orb: Orb 2 Node 5",
      "Description": "chance to cause instant death is increased while Teepo ON is active"
    },
    "dread wings": {
      "Arte Name": "Dread Wings",
      "Enabled Effects": "-",
      "Elemental Attributes": "Dark",
      "Damage Effect": "Terror",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "6[*8]",
      "Casting Time (seconds)": "3.00",
      "TP Cost": "30",
      "Requirements": "Lilium Orb: Orb 2 Node 3",
      "Description": "hit count is increased while Teepo ON is active"
    },
    "ignite terror": {
      "Arte Name": "Ignite Terror",
      "Enabled Effects": "-",
      "Elemental Attributes": "Dark",
      "Damage Effect": "Terror",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "10",
      "Casting Time (seconds)": "?",
      "TP Cost": "30",
      "Requirements": "Lilium Orb: Orb 2 Node 2",
      "Description": "-"
    },
    "scary-go-round": {
      "Arte Name": "Scary-Go-Round",
      "Elemental Attributes": "Dark",
      "Damage Effect": "Burn, Weak, Slow, Terror, Stun",
      "Damage Spread": "?",
      "Total Damage (%)": "?",
      "Max Hits": "10",
      "Requirements": "Over Limit mode must be active activated by using Ignite Terror and holding the Attack button",
      "Description": "-"
    }
  }
}

module.exports = { xillia };