/* eslint-disable */
const xillia = {
  "jude": {
    "healer": {
      "Arte Name": "Healer",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Psyche",
      "Damage Effect": "-",
      "Damage Spread": "-",
      "Total Damage (%)": "-",
      "Max Hits": "-",
      "TP Cost": "5",
      "Requirements": "-",
      "Description": "heals all allies within range in two burstsheals between 24% and 12% of max HP at a rate of 12% to 6% HP per burst depending on the distance from Judeaction speed increases after 100 and 400 useshealing range increases after 200 uses"
    },
    "recovery ring": {
      "Arte Name": "Recovery Ring",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "-",
      "Total Damage (%)": "-",
      "Max Hits": "-",
      "TP Cost": "13",
      "Requirements": "Lilium Orb: Orb 1 Node 4",
      "Description": "cures all negative status ailments for all allies within a small rangeaction speed increases after 100 and 400 useshealing range increases after 200 uses"
    },
    "demon fist": {
      "Arte Name": "Demon Fist",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "0.34 x 11.70 x 1",
      "Total Damage (%)": "204",
      "Max Hits": "2",
      "TP Cost": "6",
      "Requirements": "-",
      "Description": "projectile speed and range increase after 100 and 200 usesthe projectile penetrates targets after 400 uses"
    },
    "cerberus strike": {
      "Arte Name": "Cerberus Strike",
      "Enabled Effects": "-",
      "Elemental Attributes": "Earth",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Slow",
      "Damage Spread": "1.00 x 3",
      "Total Damage (%)": "300",
      "Max Hits": "3",
      "TP Cost": "9",
      "Requirements": "Lilium Orb: Orb 1 Node 1",
      "Description": "attack speed increases after 200 uses"
    },
    "steel": {
      "Arte Name": "Steel",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "2.00 x 1",
      "Total Damage (%)": "200",
      "Max Hits": "1",
      "TP Cost": "8",
      "Requirements": "Lilium Orb: Orb 1 Node 3",
      "Description": "increases own physical attack power by 30% for 10 secondsaction speed increases after 200 useseffect increases by 10% after 400 usesincreases own physical defense for 10 seconds after 400 uses and the Second Artes skill is equipped"
    },
    "palm strike": {
      "Arte Name": "Palm Strike",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Stun",
      "Damage Spread": "3.00 x 1",
      "Total Damage (%)": "300",
      "Max Hits": "1",
      "TP Cost": "7",
      "Requirements": "Lilium Orb: Orb 1 Node 5",
      "Description": "attack speed increases after 100 uses30% chance to inflict Stun on enemies damaged by this attack after 200 uses"
    },
    "aqua sweep": {
      "Arte Name": "Aqua Sweep",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "Water",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Weak",
      "Damage Spread": "0.80 x 3",
      "Total Damage (%)": "240",
      "Max Hits": "3",
      "TP Cost": "16",
      "Requirements": "Lilium Orb: Orb 1 Node 4",
      "Description": "knockdown enabled against enemies that can be trippedarea of effect increases after 200 uses"
    },
    "swallow dance": {
      "Arte Name": "Swallow Dance",
      "Enabled Effects": "Stand Up, Aerial",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "1.65 x 2+ 1.65 x 1",
      "Total Damage (%)": "330[*495]",
      "Max Hits": "2[*3]",
      "TP Cost": "10",
      "Requirements": "Lilium Orb: Orb 1 Node 2",
      "Description": "max hit count increases by one if the Second Artes 2 skill is equippedJude becomes airborne after executing this arteattack speed increases after 200 usesforces downed enemies to stand after 400 uses"
    },
    "talon storm": {
      "Arte Name": "Talon Storm",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "-",
      "Damage Spread": "0.84 x 5",
      "Total Damage (%)": "420",
      "Max Hits": "5",
      "TP Cost": "14",
      "Requirements": "Lilium Orb: Orb 1 Node 5",
      "Description": "attack speed increases after 200 uses"
    },
    "cyclonic surge": {
      "Arte Name": "Cyclonic Surge",
      "Enabled Effects": "Aerial",
      "Elemental Attributes": "Wind",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Paralysis",
      "Damage Spread": "1.00 x 3",
      "Total Damage (%)": "300",
      "Max Hits": "3",
      "TP Cost": "16",
      "Requirements": "Lilium Orb: Orb 2 Node 5",
      "Description": "chance to inflict Paralysis increases after 200 usesJude becomes airborne after executing this arte"
    },
    "beast": {
      "Arte Name": "Beast",
      "Enabled Effects": "Knockdown, Aerial, Guard Break",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Vitality",
      "Damage Effect": "-",
      "Damage Spread": "4.00 x 1",
      "Total Damage (%)": "400",
      "Max Hits": "1",
      "TP Cost": "14",
      "Requirements": "Lilium Orb: Orb 1 Node 8",
      "Description": "chance to Guard Break the enemy after 200 useschance to break enemy's Iron Stance effect increases after 200 uses"
    },
    "whirlwind snap": {
      "Arte Name": "Whirlwind Snap",
      "Enabled Effects": "Aerial",
      "Elemental Attributes": "Wind",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Paralysis",
      "Damage Spread": "2.50 x 1",
      "Total Damage (%)": "250",
      "Max Hits": "1",
      "TP Cost": "12",
      "Requirements": "Lilium Orb: Orb 2 Node 1",
      "Description": "enemies hit by this attack are pulled towards Judedistance pulled increases after 200 and 400 uses"
    },
    "rising falcon": {
      "Arte Name": "Rising Falcon",
      "Enabled Effects": "Aerial",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "3.50 x 1+ 0.70 x 1",
      "Total Damage (%)": "350[*420]",
      "Max Hits": "1[*2]",
      "TP Cost": "15",
      "Requirements": "Lilium Orb: Orb 1 Node 6",
      "Description": "adds an additional hit when activated from the ground after 200 uses"
    },
    "soaring vortex": {
      "Arte Name": "Soaring Vortex",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "Wind",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Paralysis",
      "Damage Spread": "3.80 x 1",
      "Total Damage (%)": "380",
      "Max Hits": "1",
      "TP Cost": "12",
      "Requirements": "Lilium Orb: Orb 1 Node 1",
      "Description": "this arte will not activate unless an enemy that is not knocked down is within rangeignores enemy Guard action and Iron Stance effectarea of effect increases after 200 uses"
    },
    "mirage blitz": {
      "Arte Name": "Mirage Blitz",
      "Enabled Effects": "Aerial",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Stun",
      "Damage Spread": "2.50 x 1+ 0.50 x 1[*0.00]",
      "Total Damage (%)": "250/300[*0]",
      "Max Hits": "1/2",
      "TP Cost": "9",
      "Requirements": "Lilium Orb: Orb 2 Node 3",
      "Description": "chance to inflict Stun on enemies damaged by this attack after 200 useschance to break enemy's Iron Stance effect increases after 200 usesattack speed increases after 400 usesthe backstep motion will deal damage after 400 usesdeals no damage if activated midair"
    },
    "raging blast": {
      "Arte Name": "Raging Blast",
      "Enabled Effects": "Stand Up, Knockdown",
      "Elemental Attributes": "Fire",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Burn",
      "Damage Spread": "1.50 x 13.00 x 1",
      "Total Damage (%)": "450",
      "Max Hits": "2",
      "TP Cost": "18",
      "Requirements": "Lilium Orb: Orb 2 Node 4",
      "Description": "chance to inflict Burn increases after 100, 200, and 400 usesforces downed enemies to stand, then returns them to a downed state"
    },
    "dragon shot": {
      "Arte Name": "Dragon Shot",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "1.05 x 12.45 x 1+ 1.05 x 1",
      "Total Damage (%)": "350/455",
      "Max Hits": "2/3",
      "TP Cost": "18",
      "Requirements": "Lilium Orb: Orb 2 Node 1",
      "Description": "Jude becomes airborne after executing this arteadds an additional hit after 200 uses"
    },
    "sun spark": {
      "Arte Name": "Sun Spark",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "Light",
      "Sub-Status Attributes": "-",
      "Damage Effect": "",
      "Damage Spread": "4.50 x 1[*5.40 x 1]",
      "Total Damage (%)": "450/540",
      "Max Hits": "1",
      "TP Cost": "20",
      "Requirements": "Lilium Orb: Orb 1 Node 6",
      "Description": "range and damage increase after 200 uses"
    },
    "phoenix plunge": {
      "Arte Name": "Phoenix Plunge",
      "Enabled Effects": "Knockdown, Aerial",
      "Elemental Attributes": "Fire",
      "Sub-Status Attributes": "Intelligence",
      "Damage Effect": "Burn",
      "Damage Spread": "2.00 x 13.00 x 1",
      "Total Damage (%)": "500",
      "Max Hits": "2",
      "TP Cost": "18",
      "Requirements": "Lilium Orb: Orb 2 Node 5",
      "Description": "Jude becomes airborne after executing this arteknockback effect is reduced after 200 usesknocks enemies higher upwards after 200 uses"
    },
    "blunt fang": {
      "Arte Name": "Blunt Fang",
      "Enabled Effects": "-",
      "Elemental Attributes": "Dark",
      "Sub-Status Attributes": "Dexterity",
      "Damage Effect": "Terror",
      "Damage Spread": "2.00 x 1",
      "Total Damage (%)": "200",
      "Max Hits": "1",
      "TP Cost": "17",
      "Requirements": "Event: acquire the Arte Tome: \"One-Hit Kill\" valuable after completing the \"The Lost Transcendental Ring\" sub-event",
      "Description": "chance to inflict Instant Death on a downed enemychance increases by 5% after 100, 200, and 400 uses"
    },
    "muzet": {
      "Arte Name": "Muzét",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "Fire, Water, Wind, Earth",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Burn, Weak, Slow, Paralysis",
      "Damage Spread": "?",
      "Total Damage (%)": "1000",
      "Max Hits": "7",
      "TP Cost": "30",
      "Requirements": "available only while Muzét is tethered to Jude",
      "Description": "first hit forces downed enemies to stand"
    },
    "immaculate healer": {
      "Arte Name": "Immaculate Healer",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Psyche",
      "Damage Effect": "-",
      "Damage Spread": "-",
      "Total Damage (%)": "-",
      "Max Hits": "-",
      "TP Cost": "5",
      "Requirements": "the Second Artes skill must be equippedreplaces Healer by holding the Artes button",
      "Description": "heals between 36% and 18% of max HP at a rate of 12% to 6% HP per burst depending on the distance from Jude"
    },
    "double demon fist": {
      "Arte Name": "Double Demon Fist",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "0.85 x 1",
      "Total Damage (%)": "85",
      "Max Hits": "1",
      "TP Cost": "0",
      "Requirements": "the Second Artes skill must be equippedextends from Demon Fist by holding the Artes button",
      "Description": "-"
    },
    "cerberus blast": {
      "Arte Name": "Cerberus Blast",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "-",
      "Damage Spread": "1.50 x 1",
      "Total Damage (%)": "150",
      "Max Hits": "1",
      "TP Cost": "0",
      "Requirements": "the Second Artes skill must be equippedextends from Cerberus Strike by holding the Artes button",
      "Description": "-"
    },
    "coil": {
      "Arte Name": "Coil",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "2.00 x 1",
      "Total Damage (%)": "200",
      "Max Hits": "1",
      "TP Cost": "8",
      "Requirements": "the Second Artes skill must be equippedreplaces Steel by holding the Artes button",
      "Description": "increases physical attack power and defense by 30% temporarily"
    },
    "reaper's toll": {
      "Arte Name": "Reaper's Toll",
      "Enabled Effects": "-",
      "Elemental Attributes": "-",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "-",
      "Damage Spread": "3.00 x 1",
      "Total Damage (%)": "300",
      "Max Hits": "1",
      "TP Cost": "7",
      "Requirements": "the Second Artes 2 skill must be equippedchains after Palm Strike by using it twice consecutively",
      "Description": "-"
    },
    "wind blade (demon fist)": {
      "Arte Name": "Wind Blade",
      "Enabled Effects": "-",
      "Elemental Attributes": "Wind",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Paralysis",
      "Damage Spread": "0.38 x 1\n1.66 x 1",
      "Total Damage (%)": "204",
      "Max Hits": "2",
      "TP Cost": "6",
      "Requirements": "- the Milla Sync skill must be equipped\n- replaces Demon Fist while linked with Milla Maxwell",
      "Description": "-"
    },
    "wind blade (double demon fist)": {
      "Arte Name": "Wind Blade",
      "Enabled Effects": "-",
      "Elemental Attributes": "Wind",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Paralysis",
      "Damage Spread": "0.34 x 1\n0.85 x 1",
      "Total Damage (%)": "119",
      "Max Hits": "2",
      "TP Cost": "0",
      "Requirements": "- the Milla Sync skill must be equipped\n- replaces Double Demon Fist while linked with Milla Maxwell",
      "Description": "-"
    },
    "grave (cerberus strike)": {
      "Arte Name": "Grave",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "Earth",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Slow",
      "Damage Spread": "1.00 x 2\n2.80 x 1",
      "Total Damage (%)": "480",
      "Max Hits": "3",
      "TP Cost": "9",
      "Requirements": "- the Milla Sync skill must be equipped\n- replaces Cerberus Strike Fist while linked with Milla Maxwell",
      "Description": "Third and fourth hits force downed enemies to stand"
    },
    "grave (cerberus blast)": {
      "Arte Name": "Grave",
      "Enabled Effects": "Stand Up",
      "Elemental Attributes": "Earth",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Slow",
      "Damage Spread": "3.00 x 1",
      "Total Damage (%)": "300",
      "Max Hits": "1",
      "TP Cost": "0",
      "Requirements": "- the Milla Sync skill must be equipped\n- replaces Cerberus Blast Fist while linked with Milla Maxwell",
      "Description": "Third and fourth hits force downed enemies to stand"
    },
    "aqua Protection (steel)": {
      "Arte Name": "Aqua Protection",
      "Enabled Effects": "-",
      "Elemental Attributes": "Water",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Weak",
      "Damage Spread": "2.00 x 6",
      "Total Damage (%)": "1200",
      "Max Hits": "6",
      "TP Cost": "8",
      "Requirements": "- the Milla Sync skill must be equipped\n- replaces Steel while linked with Milla Maxwell",
      "Description": "summons three orbs at once when activated from Coil"
    },
    "aqua Protection (soil)": {
      "Arte Name": "Aqua Protection",
      "Enabled Effects": "-",
      "Elemental Attributes": "Water",
      "Sub-Status Attributes": "-",
      "Damage Effect": "Weak",
      "Damage Spread": "2.00 x 6",
      "Total Damage (%)": "1200",
      "Max Hits": "6",
      "TP Cost": "8",
      "Requirements": "- the Milla Sync skill must be equipped\n- replaces Coil while linked with Milla Maxwell",
      "Description": "summons three orbs at once when activated from Coil"
    },
    "flare bomb (palm Strike)": {
      "Arte Name": "Flare bomb",
      "Enabled Effects": "-",
      "Elemental Attributes": "Fire",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Burn",
      "Damage Spread": "0.90 x 1",
      "Total Damage (%)": "90",
      "Max Hits": "1",
      "TP Cost": "7",
      "Requirements": "- the Milla Sync skill must be equipped\n- replaces Palm Strike linked with Milla Maxwell",
      "Description": "-"
    },
    "flare bomb (reaper's tool)": {
      "Arte Name": "Flare bomb",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "Fire",
      "Sub-Status Attributes": "Agility",
      "Damage Effect": "Burn",
      "Damage Spread": "2.10 x 1",
      "Total Damage (%)": "210",
      "Max Hits": "1",
      "TP Cost": "7",
      "Requirements": "- the Milla Sync skill must be equipped\n- replaces Reaper's Toll linked with Milla Maxwell",
      "Description": "-"
    },
    "savage roar": {
      "Arte Name": "Savage Roar",
      "Enabled Effects": "Knockdown",
      "Elemental Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "4.00 x 12.00 x 4",
      "Total Damage (%)": "1200",
      "Max Hits": "5",
      "TP Cost": "30",
      "Requirements": "Lilium Orb: Orb 2 Node 2",
      "Description": "-"
    },
    "shattering demon fist": {
      "Arte Name": "Shattering Demon Fist",
      "Enabled Effects": "Stand Up, Knockdown",
      "Elemental Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "7.50 x 1",
      "Total Damage (%)": "750",
      "Max Hits": "1",
      "TP Cost": "30",
      "Requirements": "Event: acquire the Arte Tome: \"Tremorous Fist\" valuable after completing the game",
      "Description": "-"
    },
    "final fury": {
      "Arte Name": "Final Fury",
      "Elemental Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "4500",
      "Max Hits": "13",
      "Requirements": "Over Limit mode must be active\n- activated by using Savage Roar and holding the Attack button",
      "Description": "-",
      "Enabled Effects": "-"
    },
    "tiger blade sigma": {
      "Arte Name": "Tiger Blade Sigma",
      "Elemental Attributes": "-",
      "Damage Effect": "-",
      "Damage Spread": "?",
      "Total Damage (%)": "4800",
      "Max Hits": "7",
      "Requirements": "available if a clear save file exists on the player's profile\nJude Mathis must be linked with Milla Maxwell\nOver Limit mode must be active\nactivated by using Shattering Demon Fist and holding the Attack button",
      "Description": "-",
      "Enabled Effects": "-"
    }
  }
}

module.exports = { xillia };